http:
  routers:
    dashboard:
      rule: "Host(`traefik.localtest.me`)"
      entryPoints:
        - websecure
      tls: {}
      service: api@internal
      middlewares:
        - dashboard-auth

    provisioning:
      rule: "Host(`api.localtest.me`)"
      entryPoints:
        - websecure
      tls: {}
      service: provisioning-svc

  services:
    provisioning-svc:
      loadBalancer:
        servers:
          - url: "http://provisioning-api:8000"

  middlewares:
    dashboard-auth:
      basicAuth:
        users:
          - "admin:$2y$05$DqdjcbkMIYKcHPXzzN5YiePBzhcFT55pthIWYA.ZP2SxuSY0S3iJK" # admin123
